export const data = [
  {
    image: require("../../Assets/images/main_building.jpeg"),
    text: "MEGALITH IS THE ANNUAL TECHNICAL FEST OF THE DEPARTMENT OF CIVIL ENGINEERING, INDIAN INSTITUTE OF TECHNOLOGY, KHARAGPUR HELD UNDER THE AEGIS OF THE CIVIL ENGINEERING SOCIETY, IIT KHARAGPUR AND THE PATRONAGE OF THE INSTITUTION OF CIVIL ENGINEERS (UK), IIT KHARAGPUR CHAPTER. SINCE ITS INCEPTION IN 2009, MEGALITH HAS CONQUERED A HUGE SUCCESS IN THE FIELD OF ENGINEERING AND CORPORATE SECTOR AND HAS GROWN AS LARGEST CIVIL ENGINEERING TECHNICAL FEST OF INDIA, OFFERING A DIVERSE RANGE OF COMPETITIONS, WORKSHOPS AND GUEST LECTURES.",
    bgcolor:"bg-yellow-400",
    id:1,
    heading:"About Us",
  },
  {
    image: require("../../Assets/images/megalith_fest_red.jpg"),
    text: "CAMPUS AMBASSADORS SERVE AS A CONNECTION BETWEEN THEIR COLLEGE AND OUR CAMPUS I.E. AS A NODAL POINT FOR ANY KIND OF COMMUNICATION OR PROMOTION. THIS IS A DEEPLY REWARDING OPPORTUNITY BOTH ON A PERSONAL LEVEL AND ALSO IN TERMS OF CAREER PROSPECTS AS, BEING A PART OF CAP HELPS IN PERSONALITY DEVELOPMENT BESIDES, ENHANCING YOUR MANAGERIAL SKILLS.",
    bgcolor:"bg-midnight",
    id:2,
    heading:"Megalith",
  },
  {
    image: require("../../Assets/images/megalith_entrance_two.JPG"),
    text: "",
    bgcolor:"bg-yellow-400",
    id:3,
    heading:"Know Us",
  },
];
