export const data = [
  {
    image: require("../../Assets/images/1.jpg"),
    text: "MEGALITH IS THE ANNUAL TECHNICAL FEST OF THE DEPARTMENT OF CIVIL ENGINEERING, INDIAN INSTITUTE OF TECHNOLOGY, KHARAGPUR HELD UNDER THE AEGIS OF THE CIVIL ENGINEERING SOCIETY, IIT KHARAGPUR AND THE PATRONAGE OF THE INSTITUTION OF CIVIL ENGINEERS (UK), IIT KHARAGPUR CHAPTER. SINCE ITS INCEPTION IN 2009, MEGALITH HAS CONQUERED A HUGE SUCCESS IN THE FIELD OF ENGINEERING AND CORPORATE SECTOR AND HAS GROWN AS LARGEST CIVIL ENGINEERING TECHNICAL FEST OF INDIA, OFFERING A DIVERSE RANGE OF COMPETITIONS, WORKSHOPS AND GUEST LECTURES.",
    bgcolor:"bg-yellow-400",
  },
  {
    image: require("../../Assets/images/dogukan.jpg"),
    text: "MIP INTERNS SERVE AS A CONNECTION BETWEEN THEIR COLLEGE AND OUR CAMPUS I.E. AS A NODAL POINT FOR ANY KIND OF COMMUNICATION OR PROMOTION. THIS IS A DEEPLY REWARDING OPPORTUNITY BOTH ON A PERSONAL LEVEL AND ALSO IN TERMS OF CAREER PROSPECTS AS, BEING A INTERN HELPS IN PERSONALITY DEVELOPMENT BESIDES, ENHANCING YOUR MANAGERIAL SKILLS.",
    bgcolor:"bg-midnight",
  },
  {
    image: require("../../Assets/images/norway.jpg"),
    text: "MEGALITH IS THE ANNUAL TECHNICAL FEST OF THE DEPARTMENT OF CIVIL ENGINEERING, INDIAN INSTITUTE OF TECHNOLOGY, KHARAGPUR HELD UNDER THE AEGIS OF THE CIVIL ENGINEERING SOCIETY, IIT KHARAGPUR AND THE PATRONAGE OF THE INSTITUTION OF CIVIL ENGINEERS (UK), IIT KHARAGPUR CHAPTER. SINCE ITS INCEPTION IN 2009, MEGALITH HAS CONQUERED A HUGE SUCCESS IN THE FIELD OF ENGINEERING AND CORPORATE SECTOR AND HAS GROWN AS LARGEST CIVIL ENGINEERING TECHNICAL FEST OF INDIA, OFFERING A DIVERSE RANGE OF COMPETITIONS, WORKSHOPS AND GUEST LECTURES.",
    bgcolor:"bg-yellow-400",
  },
];
